# Change these first
owner: satoshi-energy-corp # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Website (www)
    url: https://www.satoshienergy.com
  - name: Website (non-www)
    url: https://satoshienergy.com
  - name: Web App
    url: https://app.satoshienergy.com
  - name: Hasura
    url: $HASURA_URL
  - name: Blog (Ghost)
    url: https://research.satoshienergy.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.satoshienergy.com
  baseUrl: /
  logoUrl: https://app.satoshienergy.com/logo.png
  theme: dark # https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "Status of the Satoshi Energy Platform."
  introMessage: This is a status page which uses **real-time** data.
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://satoshienergy.com
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: "[Bitcoin is energy backed money.](https://satoshienergy.com)"
