# Change these first
owner: satoshi-energy-corp # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

user-agent: uptime

sites:
  - name: Website (www)
    url: https://www.satoshienergy.com
  - name: Website (non-www)
    url: https://satoshienergy.com
  - name: Blog (Ghost)
    url: https://research.satoshienergy.com
  - name: Platform/Front-end
    url: $DATA_ROOM_FRONT_END
  - name: Platform/Hasura
    url: $HASURA_URL
    maxRedirects: 10
  - name: Stargazer/Hasura
    url: $STARGAZER_HASURA
    method: POST
  - name: Stargazer/Nodejs
    url: $STARGAZER_NODEJS
  - name: ERCOT - SPP
    url: https://www.ercot.com/misapp/GetReports.do?reportTypeId=12301
  - name: ERCOT - Demand
    url: https://www.ercot.com/api/1/services/read/dashboards/supply-demand.json
  - name: ERCOT - Indicative
    url: https://www.ercot.com/content/cdr/html/rtd_ind_lmp_lz_hb_LZ_WEST.html
  - name: Noco
    url: $NOCO_URL
    maxRedirects: 10
  - name: Stargazer/CEM
    url: https://cem.satoshienergy.com
    maxRedirects: 10
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.satoshienergy.com
  baseUrl: /
  logoUrl: https://app.satoshienergy.com/logo.png
  theme: dark # https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "Status of the Satoshi Energy Platform."
  introMessage: This is a status page which uses **real-time** data.
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://satoshienergy.com
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: "[Energy finance built on bitcoin.](https://satoshienergy.com)"
